openapi: 3.0.3
info:
  title: OAuth2 Test API
  version: 1.0.0

paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: "http://127.0.0.1:8080/realms/Rikaenzhela/protocol/openid-connect/auth"
          tokenUrl: "http://127.0.0.1:8080/realms/Rikaenzhela/protocol/openid-connect/token"
          scopes:
            openid: OpenID scope
        implicit:
          authorizationUrl: "http://127.0.0.1:8080/realms/Rikaenzhela/protocol/openid-connect/auth"
          tokenUrl: "http://127.0.0.1:8080/realms/Rikaenzhela/protocol/openid-connect/token"
          scopes:
            openid: OpenID scope
        password:
          tokenUrl: "http://127.0.0.1:8080/realms/Rikaenzhela/protocol/openid-connect/token"
          scopes:
            openid: OpenID scope
        clientCredentials:
          tokenUrl: "http://127.0.0.1:8080/realms/Rikaenzhela/protocol/openid-connect/token"
          scopes:
            openid: OpenID scope

security:
  - oauth2: []